//조건에 맞는 도서 리스트 출력하기

//ORACLE 에서는 DATE 타입 출력에 TO_CHAR() 함수를 사용가능
SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE,'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK
WHERE TO_CHAR(PUBLISHED_DATE, 'YYYY') = '2021' AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE;